import type { Config } from "tailwindcss";
const config: Config = {
  darkMode: ["class"],
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        bg:          "var(--bg)",
        "bg-grain":  "var(--bg-grain)",
        surface:     "var(--surface)",
        "surface-2": "var(--surface2)",
        "surface-elev": "var(--surface-elev)",
        line:        "var(--line)",
        "line-strong": "var(--line-strong)",
        ink:         "var(--ink)",
        "ink-2":     "var(--ink-2)",
        "ink-3":     "var(--ink-3)",
        "ink-4":     "var(--ink-4)",
        accent:      "var(--accent)",
        positive:    "var(--positive)",
        negative:    "var(--negative)",
        info:        "var(--info)",
        linkedin:    "var(--accent)",
        gmaps:       "var(--positive)",
        amazon:      "var(--negative)",
      },
      borderRadius: { "2xl": "0.875rem", lg: "0.75rem", md: "0.5rem", sm: "0.25rem" },
      fontFamily: {
        geist:        ["Geist", "sans-serif"],
        "geist-mono": ["Geist Mono", "monospace"],
        instrument:   ["Instrument Serif", "serif"],
      },
      keyframes: {
        "fade-up":        { "0%": { opacity: "0", transform: "translateY(8px)" },    "100%": { opacity: "1", transform: "translateY(0)" } },
        "fade-in":        { "0%": { opacity: "0" },                                   "100%": { opacity: "1" } },
        "scale-in":       { "0%": { opacity: "0", transform: "scale(0.95)" },         "100%": { opacity: "1", transform: "scale(1)" } },
        "slide-in-right": { "0%": { opacity: "0", transform: "translateX(12px)" },    "100%": { opacity: "1", transform: "translateX(0)" } },
        "spin-slow":      { "100%": { transform: "rotate(360deg)" } },
        "toast-in":       { "0%": { opacity: "0", transform: "translateY(16px) scale(0.96)" }, "100%": { opacity: "1", transform: "translateY(0) scale(1)" } },
        "progress-bar":   { "0%": { width: "0%" }, "100%": { width: "100%" } },
        "pulse-live":     { "0%,100%": { boxShadow: "0 0 0 0 var(--positive)" }, "50%": { boxShadow: "0 0 0 8px transparent" } },
      },
      animation: {
        "fade-up":          "fade-up 0.25s ease-out",
        "fade-in":          "fade-in 0.2s ease-out",
        "scale-in":         "scale-in 0.2s cubic-bezier(0.34, 1.2, 0.64, 1)",
        "slide-in-right":   "slide-in-right 0.2s ease-out",
        "spin-slow":        "spin-slow 1s linear infinite",
        "toast-in":         "toast-in 0.3s cubic-bezier(0.34, 1.56, 0.64, 1)",
        "pulse-live":       "pulse-live 2s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
